LibraryManagementSystem/BorrowerManagement/urls.py
from django.urls import path
from . import views

app_name = "BorrowerManagement"

urlpatterns = [
    path('', views.index, name='index'),

]

LibraryManagementSystem/LibraryManagementSystem/urls.py
from django.contrib import admin
from django.urls import include, path


# from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('django.contrib.auth.urls')),
    path('', include('login.urls')),
    path('searchBook/', include('searchBook.urls')),
    path('bookCheckIn/', include('bookCheckIn.urls')),
    path('payFine/', include('payFine.urls')),
    path('BorrowerManagement/', include('BorrowerManagement.urls')),
]


admin.site.site_header = "Library Management System"
admin.site.site_title = "Search a book"

LibraryManagementSystem/login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('signup', views.register_user, name='signup'),
]

LibraryManagementSystem/BorrowerManagement/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Authors(models.Model):
    author = models.OneToOneField('BookAuthors', models.DO_NOTHING, db_column='Author_id', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'authors'


class Book(models.Model):
    isbn = models.CharField(db_column='ISBN', primary_key=True, max_length=10)  # Field name made lowercase.
    title = models.CharField(db_column='TITLE', max_length=255, blank=True, null=True)  # Field name made lowercase.
    available = models.IntegerField(db_column='AVAILABLE')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'book'


class BookAuthors(models.Model):
    author_id = models.AutoField(db_column='Author_id', primary_key=True)  # Field name made lowercase.
    isbn = models.ForeignKey(Book, models.DO_NOTHING, db_column='ISBN', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'book_authors'


class BookLoans(models.Model):
    loan_id = models.AutoField(db_column='Loan_id', primary_key=True)  # Field name made lowercase.
    isbn = models.ForeignKey(Book, models.DO_NOTHING, db_column='ISBN', blank=True, null=True)  # Field name made lowercase.
    card = models.ForeignKey('Borrower', models.DO_NOTHING, db_column='Card_id', blank=True, null=True)  # Field name made lowercase.
    date_out = models.DateField(db_column='Date_out', blank=True, null=True)  # Field name made lowercase.
    due_date = models.DateField(db_column='Due_date', blank=True, null=True)  # Field name made lowercase.
    date_in = models.DateField(db_column='Date_in', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'book_loans'


class Borrower(models.Model):
    card_id = models.AutoField(db_column='Card_id', primary_key=True)  # Field name made lowercase.
    ssn = models.CharField(db_column='Ssn', unique=True, max_length=9)  # Field name made lowercase.
    bname = models.CharField(db_column='Bname', max_length=255, blank=True, null=True)  # Field name made lowercase.
    address = models.CharField(db_column='Address', max_length=255, blank=True, null=True)  # Field name made lowercase.
    phone = models.CharField(db_column='Phone', max_length=14, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'borrower'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Fines(models.Model):
    loan = models.OneToOneField(BookLoans, models.DO_NOTHING, db_column='Loan_id', primary_key=True)  # Field name made lowercase.
    fine_amt = models.DecimalField(db_column='Fine_amt', max_digits=9, decimal_places=2)  # Field name made lowercase.
    paid = models.IntegerField(db_column='Paid', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'fines'


class Users(models.Model):
    firstname = models.CharField(db_column='firstName', max_length=255)  # Field name made lowercase.
    lastname = models.CharField(max_length=255)
    email = models.CharField(unique=True, max_length=255)
    password = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'users'

LibraryManagementSystem/BorrowerManagement/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.db import connection
from .models import Borrower

cursor = connection.cursor()

# Create your views here.


@login_required(login_url="login:login")
def index(request):
    searchValue = True
    if(request.method == "POST"):
        name = request.POST['Bname']
        ssn = request.POST['inputSSN']
        address = request.POST['inputAddress']
        phone = request.POST['inputPhoneNo']
        print(name, ssn, address, phone)
        fphno = "("
        for i in range(len(phone)):
            if i == 2:
                fphno += phone[i]+') '
            elif i == 5:
                fphno += phone[i]+'-'
            else:
                fphno += phone[i]
        print(fphno)
        cursor.execute("SELECT ssn FROM Borrower WHERE ssn = '" + ssn + "'")
        if (cursor.fetchone() == None):
            cursor.execute('INSERT INTO Borrower(Ssn,Bname,Address,Phone) VALUES("' +
                           ssn + '","' + name + '","' + address + '","' + fphno + '");')
            return render(request, "manageBorrower.html", {'searchValue': False, 'message': "Borrower added successfully"})
        else:
            return render(request, "manageBorrower.html", {'searchValue': False, 'message': "Borrower with same SSN already exist."})
    return render(request, "manageBorrower.html", {'searchValue': searchValue})

LibraryManagementSystem/BorrowerManagement/templates/manageBorrower.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Library Management System</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- <link rel="stylesheet" href="homePageCSS.css"> -->
    
    <link rel="stylesheet" href="{% static 'main.css' %}">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
</head>
<body>
    <!-- Nav bar start -->
    <nav class="nav justify-content-center">
        <a class="nav-link" href="/searchBook">Book Search</a>
        <a class="nav-link" href="/bookCheckIn">Check-In</a>
        <a class="nav-link" href="/payFine">Pay Fine</a>
        <a class="nav-link" href="/BorrowerManagement">Borrower Management</a>
        <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
    </nav>
    
    <!-- Nav bar end -->
    {% if searchValue %}
        <section class="searchResult">           
                        
                <p class = "searchHeading display-5 text-center m-3 p-1" name="searchHeading">Borrower Management</p>              
                    
                <div class="container border border-secondary w-50">                                                              
                                                
                    <form class="p-2" action="{% url 'BorrowerManagement:index' %}" method="POST">
                        {% csrf_token %}
                        
                        <div class="form-group p-2 m-2">
                          <!-- <label for="Bname">Name</label> -->
                          <input type="text" class="form-control" name="Bname" placeholder="FirstName LastName" required="1">
                        </div>                          
                        
                        <div class="form-group p-2 m-2">
                          <!-- <label for="inputAddress">Address</label> -->
                          <input type="text" class="form-control" name="inputAddress" placeholder="Address : 1234 Main St" required="1">
                        </div>                        
                        <div class="form-group p-2 m-2">
                            <!-- <label for="inputPhoneNo">Phone Number</label> -->
                            <input type="tel" class="form-control" name="inputPhoneNo" placeholder="Phone number : 1234567890" pattern="[0-9]{10}" required="1">
                        </div>
                        <div class="form-group p-2 m-2">
                            <!-- <label for="inputSSN">Social Security Number</label> -->
                            <input type="text" class="form-control" name="inputSSN" placeholder="SSN : 123456789" required="1">
                        </div>
                        <div class="input-group-append text-center p-2 m-2">
                            <button class="btn btn-outline-secondary btn-lg col-4 mx-auto" name="addbtn" type="submit">Add Borrower</button>
                        </div>
                    </form>
                </div>
                           
    {% else %}         
        </section>
        {% if message %}
                        <p class="message display-5 border border-5 text-center w-50">{{ message }}</p>
        {% endif %}
        
    {% endif %} 
    
    <!-- Footer start -->
    <footer class="page-footer">
        <p>© 2022 Copyright Vaibhav Tyagi</p>   
    </footer>
    <!-- Footer End -->
</body>
</html>