LibraryManagementSystem/LibraryManagementSystem/urls.py
from django.contrib import admin
from django.urls import include, path


# from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('django.contrib.auth.urls')),
    path('', include('login.urls')),
    path('searchBook/', include('searchBook.urls')),
    path('bookCheckIn/', include('bookCheckIn.urls')),
    path('payFine/', include('payFine.urls')),
    path('BorrowerManagement/', include('BorrowerManagement.urls')),
]


admin.site.site_header = "Library Management System"
admin.site.site_title = "Search a book"

LibraryManagementSystem/login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('signup', views.register_user, name='signup'),
]

LibraryManagementSystem/searchBook/urls.py
from django.urls import path
from . import views

app_name = "searchBook"

urlpatterns = [
    path('', views.index, name='index'),
    path('checkout/', views.checkout, name='checkout')

]

LibraryManagementSystem/searchBook/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Authors(models.Model):
    author = models.OneToOneField('BookAuthors', models.DO_NOTHING, db_column='Author_id', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'authors'


class Book(models.Model):
    isbn = models.CharField(db_column='ISBN', primary_key=True, max_length=10)  # Field name made lowercase.
    title = models.CharField(db_column='TITLE', max_length=255, blank=True, null=True)  # Field name made lowercase.
    available = models.IntegerField(db_column='AVAILABLE')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'book'


class BookAuthors(models.Model):
    author_id = models.AutoField(db_column='Author_id', primary_key=True)  # Field name made lowercase.
    isbn = models.ForeignKey(Book, models.DO_NOTHING, db_column='ISBN', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'book_authors'


class BookLoans(models.Model):
    loan_id = models.AutoField(db_column='Loan_id', primary_key=True)  # Field name made lowercase.
    isbn = models.ForeignKey(Book, models.DO_NOTHING, db_column='ISBN', blank=True, null=True)  # Field name made lowercase.
    card = models.ForeignKey('Borrower', models.DO_NOTHING, db_column='Card_id', blank=True, null=True)  # Field name made lowercase.
    date_out = models.DateField(db_column='Date_out', blank=True, null=True)  # Field name made lowercase.
    due_date = models.DateField(db_column='Due_date', blank=True, null=True)  # Field name made lowercase.
    date_in = models.DateField(db_column='Date_in', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'book_loans'


class Borrower(models.Model):
    card_id = models.AutoField(db_column='Card_id', primary_key=True)  # Field name made lowercase.
    ssn = models.CharField(db_column='Ssn', unique=True, max_length=9)  # Field name made lowercase.
    bname = models.CharField(db_column='Bname', max_length=255, blank=True, null=True)  # Field name made lowercase.
    address = models.CharField(db_column='Address', max_length=255, blank=True, null=True)  # Field name made lowercase.
    phone = models.CharField(db_column='Phone', max_length=14, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'borrower'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Fines(models.Model):
    loan = models.OneToOneField(BookLoans, models.DO_NOTHING, db_column='Loan_id', primary_key=True)  # Field name made lowercase.
    fine_amt = models.DecimalField(db_column='Fine_amt', max_digits=9, decimal_places=2)  # Field name made lowercase.
    paid = models.IntegerField(db_column='Paid', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'fines'


class Users(models.Model):
    firstname = models.CharField(db_column='firstName', max_length=255)  # Field name made lowercase.
    lastname = models.CharField(max_length=255)
    email = models.CharField(unique=True, max_length=255)
    password = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'users'

LibraryManagementSystem/searchBook/views.py
from django.contrib.auth.decorators import login_required
from msilib.schema import Condition
from pickle import NONE
from django.shortcuts import render
from django.db import connection
from .models import Book, Authors, BookAuthors
from django.core.paginator import Paginator, EmptyPage

cursor = connection.cursor()


@login_required(login_url="login:login")
def index(request):
    # flag = True
    searchValue = False
    global books_list
    print("inside index")
    # print(request)
    if (request.method == "POST"):
        if(request.POST['searchBox'] != ''):
            # flag = False
            words = request.POST['searchBox'].split(',')
            condition = ""
            for word in words:
                word = word.strip()
                word = "%"+word+"%"
                if condition != "":
                    condition += "AND"
                condition += "(bookAuthorTemp.Isbn LIKE '"+word+"' OR bookAuthorTemp.Title LIKE '" + \
                    word+"' OR bookAuthorTemp.authors LIKE '"+word+"')"
            query = "SELECT bookAuthorTemp.Isbn, bookAuthorTemp.Title, bookAuthorTemp.authors, bookAuthorTemp.Available FROM (SELECT Book.ISBN, Book.TITLE, GROUP_CONCAT(Authors.Name) authors, Book.Available FROM Book,Book_Authors,Authors WHERE Book.Isbn = Book_Authors.Isbn AND Book_Authors.Author_id = Authors.Author_id GROUP BY Book.Isbn) AS bookAuthorTemp WHERE "+condition
            cursor.execute(query)

            books_list = list(cursor.fetchall())

            p = Paginator(books_list, 6)

            page = p.get_page(1)

            return render(request, "index.html", {"page": page, "flag": False, "totalpages": p.num_pages, "searchValue": True, 'books_list': books_list})
        else:
            print("Search text box is Empty!")
            return render(request, "index.html", {"searchValue": searchValue, "flag": False})
    elif (request.method == "GET"):
        if 'previousbtn' in request.GET or 'nextbtn' in request.GET or 'firstbtn' in request.GET or 'lastbtn' in request.GET:
            print("inside else of search")
            print(request.GET.get('nextbtn'))
            print(request.GET.get('previousbtn'))
            print(request.GET.get('firstbtn'))
            print(request.GET.get('lastbtn'))
            print(books_list[:10])

            p = Paginator(books_list, 6)

            page_num = request.GET.get(
                'nextbtn') if 'nextbtn' in request.GET else request.GET.get('previousbtn') if 'previousbtn' in request.GET else request.GET.get('firstbtn') if 'firstbtn' in request.GET else request.GET.get('lastbtn')
            page = p.get_page(page_num)

            return render(request, "index.html", {"page": page, "flag": False, "totalpages": p.num_pages, "searchValue": True})

    print("Outside ifelse")
    return render(request, 'index.html', {"searchValue": searchValue, "flag": True})


def checkout(request):
    print("inside checkout")
    words = request.POST['cardno'].split(',')
    print(words)

    message = ""

    cardno = words[0]
    isbn = words[1]

    query = "SELECT COUNT(Card_id) FROM Borrower WHERE Card_id = '" + \
        cardno+"' GROUP BY Card_id"
    cursor.execute(query)

    if(cursor.fetchone() != None):
        query = "SELECT COUNT(Loan_id) FROM Book_Loans WHERE Book_Loans.Card_id = '"+str(
            cardno)+"' AND Book_Loans.Date_in IS NULL GROUP BY Book_Loans.Card_id"
        cursor.execute(query)
        result = cursor.fetchone()
        if(result == None):
            query = "SELECT Book.Available FROM Book WHERE Book.Isbn = '"+isbn+"'"
            cursor.execute(query)
            availabile = cursor.fetchone()
            if(availabile[0] == 1):
                query = 'INSERT INTO Book_Loans(Isbn, Card_id, Date_out, Due_date, Date_in) VALUES("' + \
                    isbn + '","' + \
                        str(cardno) + \
                    '",CURDATE(),DATE_ADD(Date_out,INTERVAL 14 DAY),NULL)'
                cursor.execute(query)
                query = 'UPDATE Book SET Book.Available = "0" WHERE Book.isbn = "'+isbn+'"'
                cursor.execute(query)
                message = "Successfully checked out book. Return within 14 days to avoid fine."
                query = "Select Loan_id from book_loans WHERE Book_Loans.Card_id = '" + \
                    str(cardno)+"'"
                cursor.execute(query)
                loanId = cursor.fetchall()
                print("loan id printing", loanId[-1][0])
                cursor.execute("INSERT INTO Fines(Loan_id,Fine_amt,Paid) VALUES('" +
                               str(loanId[-1][0]) + "','" + str(0.00) + "','0')")
            else:
                message = "Book is not available."
        else:
            query = "SELECT Book.Available FROM Book WHERE Book.Isbn = '"+isbn+"'"
            cursor.execute(query)
            if(result[0] < 3):
                query = 'INSERT INTO Book_Loans(Isbn, Card_id, Date_out, Due_date, Date_in) VALUES("' + \
                    isbn + '","' + \
                        str(cardno) + \
                    '",CURDATE(),DATE_ADD(Date_out,INTERVAL 14 DAY),NULL)'
                cursor.execute(query)
                query = 'UPDATE Book SET Book.Available = "0" WHERE Book.isbn = "'+isbn+'"'
                cursor.execute(query)
                message = "Successfully checked out book. Return within 14 days to avoid fine."
                query = "Select Loan_id from book_loans WHERE Book_Loans.Card_id = '" + \
                    str(cardno)+"'"
                cursor.execute(query)
                loanId = cursor.fetchall()
                print("printing loanid", type(loanId[-1][0]))
                cursor.execute("INSERT INTO Fines(Loan_id,Fine_amt,Paid) VALUES('" +
                               str(loanId[-1][0]) + "','" + str(0.00) + "','0')")
            else:
                message = "Maximum of only 3 books can be checked out by each individual."

    context = {'message': message, 'update': True}
    return render(request, 'index.html', context)

LibraryManagementSystem/searchBook/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Library Management System</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- <link rel="stylesheet" href="homePageCSS.css"> -->
    
    <link rel="stylesheet" href="{% static 'main.css' %}">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
</head>
<body>
    <!-- Nav bar start -->
    <nav class="nav justify-content-center">
        <a class="nav-link" href="/searchBook">Book Search</a>
        <a class="nav-link" href="/bookCheckIn">Check-In</a>
        <a class="nav-link" href="/payFine">Pay Fine</a>
        <a class="nav-link" href="/BorrowerManagement">Borrower Management</a>
        <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
    </nav>
    <!-- Nav bar end -->
        
        {% if not searchValue %}
        <!-- Conatiner -->
            {% if flag == True %}
                <div class="container-fluid">
                    <!-- Row start for search bar -->
                    <div class="row">
                        <div class="search-text">
                            Search a book
                        </div>
                        <form action="" method="post">
                            <div class="search-bar input-group w-50">
                                {% csrf_token %}
                                <input type="text" class="form-control" name="searchBox" placeholder="Enter Book Name,Author,ISBN">
                                <div class="input-group-append">
                                <button class="btn btn-outline-secondary" name="searchbtn" type="submit">Search</button>
                                </div>
                            </div>
                        </form>
                        
                    </div>
                    <!-- Row end for searh bar -->       
                    
                </div>
            {% elif flag == False %}                    
                    <p class="message display-5 border border-5 text-center w-50">Search text box is Empty</p>                       
            {% endif %}
        <!-- Container End -->
        {% elif searchValue %}
            <section class="searchResult"> 
                
                
                {% if page %}
                    <p class = "searchHeading text-center m-3 p-1" id="searchHeading">Search Results</p>              
                    	
                    <div class="container">                 
                                                                                
                            <p class = "pagenoheading">Page Number {{ page.number }} of {{ totalpages }}</p>
                            
                            <table id="searchtable" class="table table-striped table-bordered table-sm" >
                                <tr class = "tablecol text-center">
                                    <th>Isbn</th>
                                    <th>Title</th>
                                    <th>Author</th>
                                    <th>Available</th>
                                    <th>Check out</th>
                                </tr>
                                {% for book in page.object_list %}
                                <tr class="tablerow text-center">
                                    <td>{{ book.0 }}</td>
                                    <td>{{ book.1 }}</td>
                                    <td>{{ book.2 }}</td>
                                    <td>
                                        {% if book.3 == 1 %}
                                            Yes
                                        {% else %}
                                            No
                                        {% endif %}
                                    </td>
                                    <td>
                                        <form action="{% url 'searchBook:checkout' %}" method="POST">
                                            {% csrf_token %}
                                            <input type="hidden" name='cardno' id={{book.0}} />
                                            <button onclick="askCardNo('{{book.0}}');" class="btn btn-outline-secondary" name="checkoutbtn" type="submit">Check Out</button>
                                        </form>                                     
                                    </td>
                                </tr>
                                {% endfor %}
                            </table>
                            <form action="" id = "paginating" method= "get">
                                {% csrf_token %}
                                
                                {% if page.has_previous %}
                                <button class="btn btn-outline-secondary" name="firstbtn" type="submit" value= '{{1}}' >&laquo; First Page</button>                            
                                <button class="btn btn-outline-secondary" name="previousbtn" type="submit" value= '{{ page.previous_page_number }}' >Previous</button>
                                {% endif %}                            

                                {% if page.has_next %}
                                <button class="btn btn-outline-secondary" name="nextbtn" type="submit" value='{{ page.next_page_number }}'>Next</button>
                                <button class="btn btn-outline-secondary" name="lastbtn" type="submit" value= '{{ totalpages }}' >Last Page &raquo;</button>                                
                                {% endif %}
                                
                            </form>
                    </div>
                    
                {% else %}
                    <p class="message display-5 border border-5 text-center w-50">Book not found!</p>
                {% endif %}
                  
            </section>
        {% endif %}

        {% if update == True %}
            <p class="message display-5 border border-5 text-center w-50">{{ message }}</p>
        {% endif %}
        <script type="text/javascript">
            function askCardNo(isbn)
            {
                var card_no = prompt("Enter Card Number");
                document.getElementById(isbn).value = card_no +','+isbn;
            }
        </script>   
   

    <!-- Footer start -->
    <footer class="page-footer">
        <p>© 2022 Copyright Vaibhav Tyagi</p>   
    </footer>
    <!-- Footer End -->
</body>
</html>